### ISSUE TITLE
Split-up implementation and format description

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#18] opened 2012-09-21 11:05 UTC
The format description we're using to define our validation models could be useful for others, so let's split this up! (maybe in the documentation ?)

**Comment by leplatrem** [comment] 2013-06-12 22:30
Is this a duplicate of #53 ?

**Comment by Natim** [comment] 2014-07-24 11:34
Yes. closing as duplicate.

**Closed as completed by Natim** 2014-07-24 11:34 UTC
Labels: enhancement, priority: low
